server:
  port: 8080
  address: 127.0.0.1
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/babytun?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  redis:
    database: 2     # 数据库
    host: 127.0.0.1 # 数据库ip
    port: 6379      # 数据库端口
    jedis:
      pool:
        max-active: 100 # 最大连接数
        max-idle: 100   # 最大空闲连接数
        min-idle: 10    # 最小空闲连接数
        max-wait: 1000ms # 最大等待时间，超过1000ms没有获取到连接，则认为连接获取失败
mybatis:
  mapper-locations: classpath:mapping/*.xml
